services:
  rinhabackend.api1:
    image: rinhabackend.api
    hostname: rinhaApi1
    environment:
      - "ASPNETCORE_ENVIRONMENT=Release"
      - "ConnectionStrings__Postgres=Host=host.docker.internal;User ID=postgres;Password=postgres;Port=5432;Database=Rinha;Pooling=true;"
    networks:
      - api-network
    depends_on: 
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    build:
      context: .
      dockerfile: src/RinhaBackend.Api/Dockerfile
      
  rinhabackend.api2:
    image: rinhabackend.api
    hostname: rinhaApi2
    environment:
      - "ASPNETCORE_ENVIRONMENT=Release"
      - "ConnectionStrings__Postgres=Host=host.docker.internal;User ID=postgres;Password=postgres;Port=5432;Database=Rinha;Pooling=true;"
    networks:
      - api-network
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    build:
      context: .
      dockerfile: src/RinhaBackend.Api/Dockerfile

  nginx:
    image: nginx:latest
    networks:
      - api-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinhabackend.api1
      - rinhabackend.api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
          
  db:
    image: postgres
    networks:
      - api-network
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
          
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "joaootavio_dfdo@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Pgadmin#"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - api-network
        
networks:
  api-network:
    driver: bridge